### ISSUE TITLE
missing "tradingWithPython.lib" in the last code section of twp_103_plotting

### ISSUE THREAD

**Issue by caoyou** [sjev/twp#1]
Hi jev, I'm introducing this repo to my friends.
We were at twp_103_plotting yesterday. 
When we run the last code section, Jupyter Notebook raised an exception which said: `ModuleNotFoundError: No module named 'tradingWithPython'`
The exception is for the first line of this code section: `from tradingWithPython.lib import plotting`
Would you please upload this package, or show me where to download it?
Thank you.

**Comment by sjev** [comment]
you can pull the library from [here](https://github.com/sjev/trading-with-python)
Try to install from source dir with `pip install -e .` 
No guaratees though, I've got little time to support this nowdays.

By the way, I would suggest using `bokeh` for plotting. There is an excellent (pandas-bokeh)[https://github.com/PatrikHlobil/Pandas-Bokeh] library that produces much better plots than matplotlib.

**Comment by caoyou** [comment]
Thank you Jev! I pulled the library and got through the code section. O(∩_∩)O
